// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaw-Jl0bhQxQLiPKwycGgeN65p-iXhq6I',
    appId: '1:101641964644:web:e2ac118cddf866aa67a371',
    messagingSenderId: '101641964644',
    projectId: 'hello-e3dbc',
    authDomain: 'hello-e3dbc.firebaseapp.com',
    databaseURL: 'https://hello-e3dbc.firebaseio.com',
    storageBucket: 'hello-e3dbc.appspot.com',
    measurementId: 'G-9WLG7PJBVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZvJg0QnSEuhkzbPm5xuYYwIYX7zHpcpE',
    appId: '1:101641964644:android:bff6e910abbd245267a371',
    messagingSenderId: '101641964644',
    projectId: 'hello-e3dbc',
    databaseURL: 'https://hello-e3dbc.firebaseio.com',
    storageBucket: 'hello-e3dbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnn3ekXYoLlzjDMq7HRi--4ZG3Nq1vY7A',
    appId: '1:101641964644:ios:684e4ab95e7ea5a667a371',
    messagingSenderId: '101641964644',
    projectId: 'hello-e3dbc',
    databaseURL: 'https://hello-e3dbc.firebaseio.com',
    storageBucket: 'hello-e3dbc.appspot.com',
    iosClientId: '101641964644-2clugotv2flfq33oav4jm2estm238nur.apps.googleusercontent.com',
    iosBundleId: 'com.example.myToDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnn3ekXYoLlzjDMq7HRi--4ZG3Nq1vY7A',
    appId: '1:101641964644:ios:684e4ab95e7ea5a667a371',
    messagingSenderId: '101641964644',
    projectId: 'hello-e3dbc',
    databaseURL: 'https://hello-e3dbc.firebaseio.com',
    storageBucket: 'hello-e3dbc.appspot.com',
    iosClientId: '101641964644-2clugotv2flfq33oav4jm2estm238nur.apps.googleusercontent.com',
    iosBundleId: 'com.example.myToDo',
  );
}
